apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-webhook-service'
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '{{ .Release.Name }}-manager-webhook'
  namespace: '{{ .Release.Namespace }}'
spec:
  dnsNames:
  - '{{ .Release.Name }}-webhook-service.{{ .Release.Namespace }}.svc'
  - '{{ .Release.Name }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: '{{ .Release.Name }}-selfsigned-issuer'
  secretName: '{{ .Release.Name }}-webhook-server-cert'
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: '{{ .Release.Name }}-selfsigned-issuer'
  namespace: '{{ .Release.Namespace }}'
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/{{ .Release.Name }}-manager-webhook'
  name: '{{ .Release.Name }}-mutating-webhook-configuration'
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ .Release.Name }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-api-astarte-platform-org-v1alpha2-astarte
  failurePolicy: Fail
  name: mastarte.kb.io
  rules:
  - apiGroups:
    - api.astarte-platform.org
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - astartes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ .Release.Name }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-api-astarte-platform-org-v1alpha2-astartevoyageringress
  failurePolicy: Fail
  name: mastartevoyageringress.kb.io
  rules:
  - apiGroups:
    - api.astarte-platform.org
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - astartevoyageringresses
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ .Release.Name }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-api-astarte-platform-org-v1alpha2-flow
  failurePolicy: Fail
  name: mflow.kb.io
  rules:
  - apiGroups:
    - api.astarte-platform.org
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - flows
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ .Release.Name }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-ingress-astarte-platform-org-v1alpha1-astartedefaultingress
  failurePolicy: Fail
  name: mastartedefaultingress.kb.io
  rules:
  - apiGroups:
    - ingress.astarte-platform.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - astartedefaultingresses
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/{{ .Release.Name }}-manager-webhook'
  name: '{{ .Release.Name }}-validating-webhook-configuration'
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ .Release.Name }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-api-astarte-platform-org-v1alpha2-astarte
  failurePolicy: Fail
  name: vastarte.kb.io
  rules:
  - apiGroups:
    - api.astarte-platform.org
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - astartes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ .Release.Name }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-api-astarte-platform-org-v1alpha2-astartevoyageringress
  failurePolicy: Fail
  name: vastartevoyageringress.kb.io
  rules:
  - apiGroups:
    - api.astarte-platform.org
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - astartevoyageringresses
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ .Release.Name }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-api-astarte-platform-org-v1alpha2-flow
  failurePolicy: Fail
  name: vflow.kb.io
  rules:
  - apiGroups:
    - api.astarte-platform.org
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - flows
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ .Release.Name }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-ingress-astarte-platform-org-v1alpha1-astartedefaultingress
  failurePolicy: Fail
  name: vastartedefaultingress.kb.io
  rules:
  - apiGroups:
    - ingress.astarte-platform.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - astartedefaultingresses
  sideEffects: None
