apiVersion: v2
name: astarte-operator
description: A Helm chart for Kubernetes
type: application

version: 1.0.5
appVersion: 1.0.4
kubeVersion: ">= 1.19.0-0"

home: https://github.com/astarte-platform/astarte-kubernetes-operator
sources:
  - https://github.com/astarte-platform/astarte-kubernetes-operator
keywords:
  - astarte
  - operator
  - iot
  - dataorchestration
maintainers:
  - name: drf
    email: dario.freddi@ispirata.com
icon: https://github.com/astarte-platform/astarte-kubernetes-operator/blob/master/mascotte.svg
