apiVersion: v2
name: astarte-operator
description: The Astarte Kubernetes Operator Helm Chart.
type: application

version: "22.11.00"
appVersion: "22.11.00"
kubeVersion: ">= 1.19.0-0"

home: https://github.com/astarte-platform/astarte-kubernetes-operator
sources:
  - https://github.com/astarte-platform/astarte-kubernetes-operator
keywords:
  - astarte
  - operator
  - iot
  - dataorchestration
maintainers:
  - name: drf
    email: dario.freddi@ispirata.com
icon: https://github.com/astarte-platform/astarte-kubernetes-operator/blob/master/mascotte.svg
